[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.memory_type = qio_qspi
build_flags = 
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    
    ; --- НАСТРОЙКИ ДИСПЛЕЯ TFT_eSPI ---
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=240
    -DTFT_MOSI=20
    -DTFT_SCLK=19
    -DTFT_CS=-1
    -DTFT_DC=47
    -DTFT_RST=21
    -DTFT_BL=38
    -DTFT_BACKLIGHT_ON=HIGH
    
    ; --- КЛЮЧЕВЫЕ ФИКСЫ ДЛЯ УСТРАНЕНИЯ BOOTLOOP ---
    -DUSE_HSPI_PORT=1
    -DSPI_FREQUENCY=10000000
    -DSPI_READ_FREQUENCY=6000000
    -DLOAD_GLCD=1

lib_deps = 
    bodmer/TFT_eSPI@^2.5.43
    madhephaestus/ESP32Servo@^1.2.1